name: ".NET"

on:
  push:
    branches: ["trunk"]
  pull_request:
    branches: ["trunk"]

jobs:
  build:
    runs-on: "ubuntu-latest"

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          ACCEPT_EULA: "Y"
          MSSQL_SA_PASSWORD: "BXYA5JMvM3PweSwB"
        ports:
        - 1433:1433
        options: --user root

    steps:
    - uses: "actions/checkout@v4"
    
    - name: "Setup .NET"
      uses: "actions/setup-dotnet@v4"
      with:
        dotnet-version: "9.0.x"
        
    - name: "Restore dependencies"
      run: "dotnet restore"
      
    - name: "Build"
      run: "dotnet build --no-restore"
      
    - name: "Test"
      run: |
        dotnet test --no-build --verbosity normal
      env:
        ConnectionStrings__Test: "User ID='sa'; Password='BXYA5JMvM3PweSwB'; Server='localhost'; Encrypt='False'; Initial Catalog='EpcTests'"
